language: dart
dart:
  - dev
cache:
  directories:
    - $HOME/.pub-cache

# TODO: Use chrome in --headless mode once supported by pub run test.
dist: trusty
addons:
  chrome: stable

branches:
  only: [master]

# Check for analysis issues, run the test cases, and ensure `dartfmt` is run.
dart_task:
  - test: --platform vm
  - dartanalyzer
  - dartfmt

# TODO: Test with dartdevc once https://github.com/dart-lang/sdk/issues/30810.
