name: code_builder
version: 2.0.0-alpha+1
description: A fluent API for generating Dart code
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/code_builder

environment:
  sdk: '>=1.22.0 <2.0.0-dev.infinity'

dependencies:
  built_collection: ^1.0.0
  built_value: ^1.0.0
  dart_style: ^1.0.0
  matcher: ^0.12.0
  meta: ^1.0.5

dev_dependencies:
  build_runner: ^0.3.0
  built_value_generator: '>=1.0.0 <=1.1.4'
  source_gen: '>=0.5.0 <0.7.0'
  test: ^0.12.0

transformers:
  - test/pub_serve:
      $include: test/**_test.dart
