name: code_builder
version: 2.0.0-alpha+2
description: A fluent API for generating Dart code
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/code_builder

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  built_collection: ^1.0.0
  built_value: '>=2.0.0 <5.0.0'
  dart_style: ^1.0.0
  matcher: ^0.12.0
  meta: ^1.0.5

dev_dependencies:
  build_runner: '>=0.4.0 <0.6.0'
  built_value_generator: '>=2.0.0 <5.0.0'
  io: '>=0.1.0 <0.3.0'
  source_gen: '^0.7.0'
  test: ^0.12.0
