name: code_builder
version: 2.0.0-dev
description: A fluent API for generating Dart code
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/code_builder

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  meta: ^1.0.2

dev_dependencies:
  test: ^0.12.0
