name: code_builder
version: 0.1.0-dev+2
description: A fluent API for generating Dart code
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/code_builder

environment:
  sdk: '>=1.9.1 <2.0.0'

dependencies:
  analyzer:
  dart_style:
  matcher: ^0.12.0+2
  meta: ^1.0.2

dev_dependencies:
  test: ^0.12.0

dependency_overrides:
  # As of 9-13-2016, this is the internal SHA. This means we can't publish to
  # pub, but at least can develop with code that will work out of the box on
  # the internal repo.
  analyzer: 0.29.0-alpha.0
